'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Share2, Download, Link, CheckCheck, FileText } from 'lucide-react';
import { HistoricalScene } from '@/types/story';

interface ShareExportPanelProps {
  scenes: HistoricalScene[];
  searchQuery: string;
  currentLang: 'EN' | 'HI';
  onToastSuccess: (msg: string) => void;
  onToastError: (msg: string) => void;
}

export default function ShareExportPanel({
  scenes,
  searchQuery,
  currentLang,
  onToastSuccess,
  onToastError,
}: ShareExportPanelProps) {
  const [linkCopied, setLinkCopied] = useState(false);

  // ── Share: copy URL to clipboard ─────────────────────────────────────────
  const handleShareJourney = async () => {
    try {
      const url = new URL(window.location.href);
      url.searchParams.set('witness', encodeURIComponent(searchQuery));
      await navigator.clipboard.writeText(url.toString());
      setLinkCopied(true);
      onToastSuccess(
        currentLang === 'EN'
          ? '🔗 Link copied to clipboard! Share your historical journey.'
          : '🔗 लिंक क्लिपबोर्ड पर कॉपी हो गया!'
      );
      setTimeout(() => setLinkCopied(false), 2500);
    } catch {
      onToastError(
        currentLang === 'EN'
          ? 'Could not copy link. Please copy the URL manually.'
          : 'लिंक कॉपी नहीं हो सका।'
      );
    }
  };

  // ── Export: download .txt summary ────────────────────────────────────────
  const handleDownloadSummary = () => {
    try {
      const lines: string[] = [
        '╔══════════════════════════════════════════════════════════╗',
        '║          TIMEWITNESS — HISTORICAL JOURNEY SUMMARY        ║',
        '╚══════════════════════════════════════════════════════════╝',
        '',
        `Topic   : ${searchQuery}`,
        `Language: ${currentLang === 'EN' ? 'English' : 'Hindi (हिन्दी)'}`,
        `Generated: ${new Date().toLocaleString()}`,
        '',
        '══════════════════════════════════════════════════════════════',
        '',
      ];

      scenes.forEach((scene) => {
        lines.push(`SCENE ${scene.sceneNumber} OF 5 — ${scene.era}`);
        lines.push(`Title: ${scene.title}`);
        lines.push('');
        lines.push(scene.narration);
        lines.push('');
        lines.push(`[Ambient: ${scene.ambientTag}]`);
        lines.push('──────────────────────────────────────────────────────────');
        lines.push('');
      });

      lines.push('Generated by TimeWitness AI Engine · Powered by Google Gemini');
      lines.push('https://timewitness.ai');

      const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `TimeWitness_${searchQuery.replace(/\s+/g, '_').slice(0, 40)}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      onToastSuccess(
        currentLang === 'EN'
          ? '📄 Story summary downloaded successfully!'
          : '📄 कहानी सारांश डाउनलोड हो गया!'
      );
    } catch {
      onToastError(
        currentLang === 'EN'
          ? 'Download failed. Please try again.'
          : 'डाउनलोड विफल हुआ।'
      );
    }
  };

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: 16 }}
        transition={{ duration: 0.35, ease: 'easeOut' }}
        className="mt-6 p-4 rounded-2xl bg-gradient-to-r from-[#1B1B26] to-[#14141C] border border-[#D4AF37]/25 flex flex-col sm:flex-row items-center gap-4"
      >
        {/* Label */}
        <div className="flex items-center gap-2 flex-1 min-w-0">
          <Share2 className="w-4 h-4 text-[#D4AF37] shrink-0" />
          <div className="min-w-0">
            <p className="text-xs font-bold text-[#F8FAFC]">
              {currentLang === 'EN' ? 'Journey Complete!' : 'यात्रा पूर्ण!'}
            </p>
            <p className="text-[11px] text-[#64748B] truncate">
              {currentLang === 'EN'
                ? 'Share or export your full 5-scene historical journey'
                : 'अपनी 5-दृश्य ऐतिहासिक यात्रा साझा करें या निर्यात करें'}
            </p>
          </div>
        </div>

        {/* Buttons */}
        <div className="flex items-center gap-2 shrink-0">
          {/* Share Journey */}
          <motion.button
            whileHover={{ scale: 1.04 }}
            whileTap={{ scale: 0.96 }}
            onClick={handleShareJourney}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-[#D4AF37] text-[#0D0D11] text-xs font-bold transition-all hover:bg-[#FFF3C4] shadow-gold-glow"
          >
            {linkCopied ? (
              <>
                <CheckCheck className="w-3.5 h-3.5" />
                <span>{currentLang === 'EN' ? 'Copied!' : 'कॉपी!'}</span>
              </>
            ) : (
              <>
                <Link className="w-3.5 h-3.5" />
                <span>{currentLang === 'EN' ? 'Share Journey' : 'यात्रा साझा करें'}</span>
              </>
            )}
          </motion.button>

          {/* Download Summary */}
          <motion.button
            whileHover={{ scale: 1.04 }}
            whileTap={{ scale: 0.96 }}
            onClick={handleDownloadSummary}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-[#1B1B26] border border-[#242434] hover:border-[#D4AF37]/50 text-xs font-bold text-[#94A3B8] hover:text-[#F8FAFC] transition-all"
          >
            <FileText className="w-3.5 h-3.5 text-[#D4AF37]" />
            <span>{currentLang === 'EN' ? 'Download Summary' : 'सारांश डाउनलोड'}</span>
          </motion.button>
        </div>
      </motion.div>
    </AnimatePresence>
  );
}
