'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, ChevronUp, ExternalLink, BookOpen, Scroll, Globe, GraduationCap } from 'lucide-react';

export interface HistoricalSource {
  id?: string;
  title: string;
  publisher?: string;
  year?: string;
  url?: string;
  relevance?: string;
  source_type?: 'primary' | 'secondary' | 'digital' | 'academic' | string;
}

interface SourcesPanelProps {
  sources?: HistoricalSource[];
  topic?: string;
  /** Fallback sources generated for any topic when no DB sources exist */
  showFallbackSources?: boolean;
}

function getSourceIcon(type: string | undefined) {
  switch (type) {
    case 'primary':   return <Scroll className="w-3.5 h-3.5 text-amber-400" />;
    case 'academic':  return <GraduationCap className="w-3.5 h-3.5 text-purple-400" />;
    case 'digital':   return <Globe className="w-3.5 h-3.5 text-cyan-400" />;
    default:          return <BookOpen className="w-3.5 h-3.5 text-emerald-400" />;
  }
}

function getSourceTypeBadge(type: string | undefined) {
  const configs: Record<string, { label: string; color: string }> = {
    primary:   { label: 'Primary Source', color: 'text-amber-300 bg-amber-900/30 border-amber-500/30' },
    academic:  { label: 'Academic',       color: 'text-purple-300 bg-purple-900/30 border-purple-500/30' },
    digital:   { label: 'Digital',        color: 'text-cyan-300 bg-cyan-900/30 border-cyan-500/30' },
    secondary: { label: 'Secondary',      color: 'text-emerald-300 bg-emerald-900/30 border-emerald-500/30' },
  };
  const config = configs[type ?? 'secondary'] ?? configs.secondary;
  return (
    <span className={`text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border ${config.color}`}>
      {config.label}
    </span>
  );
}

function generateFallbackSources(topic: string): HistoricalSource[] {
  return [
    {
      title: `Wikipedia: ${topic}`,
      publisher: 'Wikipedia Foundation',
      year: new Date().getFullYear().toString(),
      url: `https://en.wikipedia.org/wiki/${encodeURIComponent(topic.replace(/\s+/g, '_'))}`,
      relevance: 'General encyclopedic overview and links to primary sources.',
      source_type: 'digital',
    },
    {
      title: 'AI-Generated Historical Narrative',
      publisher: 'TimeWitness / Google Gemini 2.5 Flash',
      year: new Date().getFullYear().toString(),
      relevance:
        'This experience was generated by Google Gemini AI. All narrative elements should be verified against primary historical sources.',
      source_type: 'digital',
    },
    {
      title: 'TimeWitness Historical Evidence Standards',
      publisher: 'TimeWitness Engine',
      relevance:
        'Scenes are classified as Historical Fact (verified), AI Reconstruction (dramatized from records), or Simulation (hypothetical).',
      source_type: 'secondary',
    },
  ];
}

export default function SourcesPanel({ sources, topic = 'this historical topic', showFallbackSources = true }: SourcesPanelProps) {
  const [isOpen, setIsOpen] = useState(false);

  const displaySources =
    sources && sources.length > 0
      ? sources
      : showFallbackSources
      ? generateFallbackSources(topic)
      : [];

  if (displaySources.length === 0) return null;

  return (
    <div className="mt-4 rounded-2xl border border-[#242434] bg-[#0D0D11]/80 overflow-hidden">
      {/* Accordion Header */}
      <button
        onClick={() => setIsOpen((o) => !o)}
        className="w-full flex items-center justify-between px-4 py-3 hover:bg-[#14141C] transition-colors group"
      >
        <div className="flex items-center gap-2.5">
          <BookOpen className="w-4 h-4 text-[#D4AF37]" />
          <span className="text-xs font-bold text-[#F8FAFC] uppercase tracking-wider">
            Sources & Historical Context
          </span>
          <span className="text-[10px] font-mono text-[#64748B] bg-[#1B1B26] px-2 py-0.5 rounded-full border border-[#242434]">
            {displaySources.length}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-[10px] text-[#64748B] group-hover:text-[#94A3B8] transition-colors">
            {isOpen ? 'Collapse' : 'Expand sources'}
          </span>
          {isOpen
            ? <ChevronUp className="w-4 h-4 text-[#D4AF37]" />
            : <ChevronDown className="w-4 h-4 text-[#64748B] group-hover:text-[#D4AF37] transition-colors" />
          }
        </div>
      </button>

      {/* Accordion Body */}
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            key="sources-body"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25, ease: 'easeInOut' }}
            className="overflow-hidden"
          >
            <div className="px-4 pb-4 space-y-3 border-t border-[#242434] pt-3">
              {/* Evidence legend */}
              <div className="flex flex-wrap gap-2 mb-3 pb-3 border-b border-[#1B1B26]">
                <span className="text-[9px] text-[#64748B] uppercase tracking-wider self-center">Evidence Legend:</span>
                <span className="text-[9px] px-2 py-0.5 rounded-full bg-amber-900/30 border border-amber-500/30 text-amber-300 font-bold">📜 Historical Fact</span>
                <span className="text-[9px] px-2 py-0.5 rounded-full bg-purple-900/30 border border-purple-500/30 text-purple-300 font-bold">🎭 AI Reconstruction</span>
                <span className="text-[9px] px-2 py-0.5 rounded-full bg-cyan-900/30 border border-cyan-500/30 text-cyan-300 font-bold">🔮 Simulation</span>
              </div>

              {displaySources.map((src, i) => (
                <div
                  key={src.id ?? i}
                  className="p-3 rounded-xl bg-[#14141C] border border-[#1B1B26] hover:border-[#2A2A3A] transition-colors"
                >
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-start gap-2 min-w-0 flex-1">
                      <div className="mt-0.5 flex-shrink-0">{getSourceIcon(src.source_type)}</div>
                      <div className="min-w-0">
                        <p className="text-xs font-bold text-[#F8FAFC] leading-snug truncate">
                          {src.title}
                        </p>
                        <div className="flex items-center gap-2 mt-1 flex-wrap">
                          {src.publisher && (
                            <span className="text-[10px] text-[#64748B]">{src.publisher}</span>
                          )}
                          {src.year && (
                            <span className="text-[10px] text-[#64748B]">· {src.year}</span>
                          )}
                          {getSourceTypeBadge(src.source_type)}
                        </div>
                        {src.relevance && (
                          <p className="text-[11px] text-[#94A3B8] mt-1.5 leading-relaxed">
                            {src.relevance}
                          </p>
                        )}
                      </div>
                    </div>
                    {src.url && (
                      <a
                        href={src.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex-shrink-0 p-1.5 rounded-lg bg-[#1B1B26] border border-[#242434] hover:border-[#D4AF37]/50 hover:bg-[#D4AF37]/10 transition-all group"
                        title="Open source"
                      >
                        <ExternalLink className="w-3.5 h-3.5 text-[#64748B] group-hover:text-[#D4AF37] transition-colors" />
                      </a>
                    )}
                  </div>
                </div>
              ))}

              <p className="text-[10px] text-[#475569] italic text-center pt-1">
                TimeWitness classifies all content by evidence type. AI-generated narratives are reconstructions, not primary sources.
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
