'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, ChevronUp, ExternalLink, BookOpen, Scroll, Globe, GraduationCap } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';

export interface HistoricalSource {
  id?: string;
  title: string;
  publisher?: string;
  year?: string;
  url?: string;
  relevance?: string;
  source_type?: 'primary' | 'secondary' | 'digital' | 'academic' | string;
}

interface SourcesPanelProps {
  sources?: HistoricalSource[];
  topic?: string;
  showFallbackSources?: boolean;
}

function getSourceIcon(type: string | undefined) {
  switch (type) {
    case 'primary':   return <Scroll className="w-3.5 h-3.5 text-amber-400" />;
    case 'academic':  return <GraduationCap className="w-3.5 h-3.5 text-purple-400" />;
    case 'digital':   return <Globe className="w-3.5 h-3.5 text-cyan-400" />;
    default:          return <BookOpen className="w-3.5 h-3.5 text-emerald-400" />;
  }
}

function getSourceTypeBadge(type: string | undefined, currentLang: string) {
  const isEn = currentLang === 'EN';
  const configs: Record<string, { label: string; color: string }> = {
    primary:   { label: isEn ? 'Primary Source' : currentLang === 'HI' ? 'प्राथमिक स्रोत' : 'Primary Source', color: 'text-amber-300 bg-amber-900/30 border-amber-500/30' },
    academic:  { label: isEn ? 'Academic' : currentLang === 'HI' ? 'शैक्षणिक' : 'Academic',       color: 'text-purple-300 bg-purple-900/30 border-purple-500/30' },
    digital:   { label: isEn ? 'Digital' : currentLang === 'HI' ? 'डिजिटल' : 'Digital',        color: 'text-cyan-300 bg-cyan-900/30 border-cyan-500/30' },
    secondary: { label: isEn ? 'Secondary' : currentLang === 'HI' ? 'द्वितीयक' : 'Secondary',      color: 'text-emerald-300 bg-emerald-900/30 border-emerald-500/30' },
  };
  const config = configs[type ?? 'secondary'] ?? configs.secondary;
  return (
    <span className={`text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border ${config.color}`}>
      {config.label}
    </span>
  );
}

function generateFallbackSources(topic: string, currentLang: string): HistoricalSource[] {
  const isEn = currentLang === 'EN';
  return [
    {
      title: `Wikipedia: ${topic}`,
      publisher: 'Wikipedia Foundation',
      year: new Date().getFullYear().toString(),
      url: `https://en.wikipedia.org/wiki/${encodeURIComponent(topic.replace(/\s+/g, '_'))}`,
      relevance: isEn ? 'General encyclopedic overview and links to primary sources.' : 'सामान्य अवलोकन और प्राथमिक स्रोतों के लिंक।',
      source_type: 'digital',
    },
    {
      title: isEn ? 'AI-Generated Historical Narrative' : 'AI-जनरेटेड ऐतिहासिक कथा',
      publisher: 'TimeWitness / Google Gemini 2.5 Flash',
      year: new Date().getFullYear().toString(),
      relevance: isEn 
        ? 'This experience was generated by Google Gemini AI. All narrative elements should be verified against primary historical sources.'
        : 'यह अनुभव गूगल जेमिनी AI द्वारा जनरेट किया गया है।',
      source_type: 'digital',
    },
    {
      title: isEn ? 'TimeWitness Historical Evidence Standards' : 'TimeWitness ऐतिहासिक साक्ष्य मानक',
      publisher: 'TimeWitness Engine',
      relevance: isEn 
        ? 'Scenes are classified as Historical Fact (verified), AI Reconstruction (dramatized from records), or Simulation (hypothetical).'
        : 'दृश्यों को ऐतिहासिक तथ्य, एआई पुनर्निर्माण, या सिमुलेशन के रूप में वर्गीकृत किया गया है।',
      source_type: 'secondary',
    },
  ];
}

export default function SourcesPanel({ sources, topic = 'this historical topic', showFallbackSources = true }: SourcesPanelProps) {
  const { currentLang } = useLanguage();
  const [isOpen, setIsOpen] = useState(false);

  const displaySources =
    sources && sources.length > 0
      ? sources
      : showFallbackSources
      ? generateFallbackSources(topic, currentLang)
      : [];

  if (displaySources.length === 0) return null;

  const isEn = currentLang === 'EN';
  const headerTitle = isEn ? 'Sources & Historical Context' : currentLang === 'HI' ? 'स्रोत और ऐतिहासिक संदर्भ' : 'Sources & Historical Context';
  const expandText = isOpen ? (isEn ? 'Collapse' : 'संक्षिप्त करें') : (isEn ? 'Expand sources' : 'स्रोत विस्तृत करें');
  const legendLabel = isEn ? 'Evidence Legend:' : 'साक्ष्य संकेत:';
  const factLabel = isEn ? 'Historical Fact' : 'ऐतिहासिक तथ्य';
  const reconLabel = isEn ? 'AI Reconstruction' : 'एआई पुनर्निर्माण';
  const simLabel = isEn ? 'Simulation' : 'सिमुलेशन';
  const footerText = isEn 
    ? 'TimeWitness classifies all content by evidence type. AI-generated narratives are reconstructions, not primary sources.'
    : 'TimeWitness सभी सामग्री को साक्ष्य प्रकार से वर्गीकृत करता है। एआई-जनित आख्यान पुनर्निर्माण हैं, प्राथमिक स्रोत नहीं।';

  return (
    <div className="mt-4 rounded-2xl border border-[#242434] bg-[#0D0D11]/80 overflow-hidden">
      <button
        onClick={() => setIsOpen((o) => !o)}
        className="w-full flex items-center justify-between px-4 py-3 hover:bg-[#14141C] transition-colors group"
      >
        <div className="flex items-center gap-2.5">
          <BookOpen className="w-4 h-4 text-[#D4AF37]" />
          <span className="text-xs font-bold text-[#F8FAFC] uppercase tracking-wider">
            {headerTitle}
          </span>
          <span className="text-[10px] font-mono text-[#64748B] bg-[#1B1B26] px-2 py-0.5 rounded-full border border-[#242434]">
            {displaySources.length}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-[10px] text-[#64748B] group-hover:text-[#94A3B8] transition-colors">
            {expandText}
          </span>
          {isOpen
            ? <ChevronUp className="w-4 h-4 text-[#D4AF37]" />
            : <ChevronDown className="w-4 h-4 text-[#64748B] group-hover:text-[#D4AF37] transition-colors" />
          }
        </div>
      </button>

      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            key="sources-body"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25, ease: 'easeInOut' }}
            className="overflow-hidden"
          >
            <div className="px-4 pb-4 space-y-3 border-t border-[#242434] pt-3">
              <div className="flex flex-wrap gap-2 mb-3 pb-3 border-b border-[#1B1B26]">
                <span className="text-[9px] text-[#64748B] uppercase tracking-wider self-center">{legendLabel}</span>
                <span className="text-[9px] px-2 py-0.5 rounded-full bg-amber-900/30 border border-amber-500/30 text-amber-300 font-bold">📜 {factLabel}</span>
                <span className="text-[9px] px-2 py-0.5 rounded-full bg-purple-900/30 border border-purple-500/30 text-purple-300 font-bold">🎭 {reconLabel}</span>
                <span className="text-[9px] px-2 py-0.5 rounded-full bg-cyan-900/30 border border-cyan-500/30 text-cyan-300 font-bold">🔮 {simLabel}</span>
              </div>

              {displaySources.map((src, i) => (
                <div
                  key={src.id ?? i}
                  className="p-3 rounded-xl bg-[#14141C] border border-[#1B1B26] hover:border-[#2A2A3A] transition-colors"
                >
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-start gap-2 min-w-0 flex-1">
                      <div className="mt-0.5 flex-shrink-0">{getSourceIcon(src.source_type)}</div>
                      <div className="min-w-0">
                        <p className="text-xs font-bold text-[#F8FAFC] leading-snug truncate">
                          {src.title}
                        </p>
                        <div className="flex items-center gap-2 mt-1 flex-wrap">
                          {src.publisher && (
                            <span className="text-[10px] text-[#64748B]">{src.publisher}</span>
                          )}
                          {src.year && (
                            <span className="text-[10px] text-[#64748B]">· {src.year}</span>
                          )}
                          {getSourceTypeBadge(src.source_type, currentLang)}
                        </div>
                        {src.relevance && (
                          <p className="text-[11px] text-[#94A3B8] mt-1.5 leading-relaxed">
                            {src.relevance}
                          </p>
                        )}
                      </div>
                    </div>
                    {src.url && (
                      <a
                        href={src.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex-shrink-0 p-1.5 rounded-lg bg-[#1B1B26] border border-[#242434] hover:border-[#D4AF37]/50 hover:bg-[#D4AF37]/10 transition-all group"
                        title="Open source"
                      >
                        <ExternalLink className="w-3.5 h-3.5 text-[#64748B] group-hover:text-[#D4AF37] transition-colors" />
                      </a>
                    )}
                  </div>
                </div>
              ))}

              <p className="text-[10px] text-[#475569] italic text-center pt-1">
                {footerText}
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
